parameters:
    tables.aught13.postlove: %core.table_prefix%posts_likes
services:
    aught13.postlove.listener:
        class: aught13\postlove\event\main_listener
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @template
            - @user
            - @controller.helper
            - %tables.aught13.postlove%
        tags:
            - { name: event.listener }
    aught13.postlove.ajaxify:
        class: aught13\postlove\controller\ajaxify
        arguments:
            - @config
            - @dbal.conn
            - @user
            - @aught13.postlove.notifyhelper
            - %tables.aught13.postlove%
    aught13.postlove.lovelist:
        class: aught13\postlove\controller\lovelist
        arguments:
            - @user
            - @language
            - @controller.helper
            - @dbal.conn
            - @auth
            - @user_loader
            - @template
            - @pagination
            - @request
            - %tables.aught13.postlove%
            - %core.root_path%
    aught13.postlove.notifyhelper:
        class: aught13\postlove\controller\notifyhelper
        arguments:
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @service_container
            - %core.root_path%
            - %core.php_ext%
    notification.type.postlove:
        class: aught13\postlove\notification\postlove
        shared : false # shared MUST be false for this to work!
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @language
            - @auth
            - @config
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }